# Generated by Django 5.2.17 on 2026-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('target_language', models.CharField(max_length=64)),
                ('detected_language', models.CharField(blank=True, max_length=64)),
                ('detected_language_code', models.CharField(blank=True, max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='translate_t_session_fd6f39_idx')],
            },
        ),
    ]
